### ISSUE TITLE
Find wrong keys with ide-extension

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang#1057]
During opening PRs I found a lots of projects that use a wrong key in the code. Like in this PR: https://github.com/labring/sealos/pull/3474#issuecomment-1623871541

This wrong key is not yet appearing in any report. Do we plan to add that somehow? I feel like that could be helpful. What do you guys think?

@inlang/ide-extension @inlang/cli

**Comment by felixhaeberle** [comment]
– The CLI can not detect non-existent keys.
- The IDE Extension already says that no key is found in the reference language

@NilsJacobsen I don't see any improvements here, or did I miss something?

**Comment by felixhaeberle** [comment]
Currently, we do not offer such a functionality. This would require scanning the complete repository with a matcher/parser-like approach which we do with the IDE Extension already (`messageReferencePatterns`). 

I suggest converting this issue into a discussion and see if people are using it in the same way as you do and if there is an interest in such a feature, build it.
