### ISSUE TITLE
`lint` command outputs misleading message

### ISSUE THREAD

**Issue by ivanhofer** [opral/inlang#1058]
## Problem

The lint command outputs a success message even if no lint rules are configured.

### Expected behavior

The `lint` command should fail if no lint rules are defined.

### Additional information

- `inlang.config.js` file:

```js
/**
  * @type { import("@inlang/core/config").DefineConfig }
  */
export async function defineConfig(env) {
  const { default: typesafeI18nPlugin } = await env.$import('https://cdn.jsdelivr.net/gh/ivanhofer/inlang-plugin-typesafe-i18n@2/dist/index.js');

  const { default: standardLintRules } = await env.$import('https://cdn.jsdelivr.net/npm/@inlang/plugin-standard-lint-rules@3/dist/index.js');

  return {
    referenceLanguage: 'en',
    plugins: [
      typesafeI18nPlugin(),
      standardLintRules(),
    ],
  };
}
```

- `npx @inlang/cli lint`:

![image](https://github.com/inlang/inlang/assets/21335119/e5484a87-37ed-4694-8be6-7479a8d7822f)

**Comment by ivanhofer** [comment]
I would also rephrase the success message a bit. "Everything translated correctly." is not really the case if the messages contain grammar issues ^^. Maybe "Could not find any vialoation of configured lint rules in your messages" or something else more technical.

**Comment by felixhaeberle** [comment]
Thanks for the feedback. I will improve the lint command. 👍

**Comment by ivanhofer** [comment]
Also the link here points to the deprecated repository. [I would suggest we change it to the docs page: ](https://github.com/inlang/inlang/tree/main/source-code/plugins/standard-lint-rules) is the correct link.

**Comment by ivanhofer** [comment]
Also the links on the [docs page](https://inlang.com/documentation/apps/inlang-cli#lint
) open to the old repo

**Comment by ivanhofer** [comment]
Hmm ok double confusion ^^

The lint rules are configured already, but the info message is misleading ^^

This is acutally the output when you don't specify lint rules:
![image](https://github.com/inlang/inlang/assets/21335119/a8c011da-dbd7-4449-979c-9c89b23273f0)

But still, the success message is here, which should not in this case. Also the error message should clearly show that there are no lint rules configured. The contents of the information message would be perfect here to guide the user how to fix the problem.
But I think the message should only show up if no lint rules are set up. In all other cases I would remove it.

**Comment by felixhaeberle** [comment]
We need real tests for the CLI also. 😄
Weird, it should return and not print the success message when there is an error.

**Comment by felixhaeberle** [comment]
The `lint` command now checks if lint rules are configured or not and gives better error messages based on that.
