### ISSUE TITLE
Globalize inlang (website)

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang#1063]
After we set up the i18n lib for inlang #1062 we can extract all messages and translate. With inlang's semi-automated tools, that should be done quickly.

- [x] Extract all messages with ide-extension
- [x] machine translate it with cli

@inlang/editor

**Comment by NiklasBuchfink** [comment]
@NilsJacobsen I'm hyped to do this and note everything we encounter. I think we get great insights into technical problems and UX issues 💪 

We can use the Internationalization API for time formatting, currency, etc.

**Comment by NilsJacobsen** [comment]
I would take en, de and maybe zh for now. What do you think?

**Comment by NiklasBuchfink** [comment]
`zh` would simply be `machine translate` at the moment, right?
