### ISSUE TITLE
inlang.com/install should preserve formatting of json

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang#1372]
## Problem 

Installing a module via the website does not preserve the formatting of the project settings file, leading to a large changelog. See https://github.com/samuelstroschein/translation/commit/b43f3228fd5ccbfa956c93f02d6cd25a977c956a

## Proposal

Detect and preserve the formatting (tabs or spaces and end of line) to keep changes small.

**Comment by samuelstroschein** [comment]
The detect json formatting logic should be included in the SDK too. 

https://github.com/inlang/monorepo/blob/f6c267675835cf1c3376ca32a94bde81d1c9decf/inlang/source-code/sdk/src/loadProject.ts#L266-L269

**Comment by NiklasBuchfink** [comment]
Work in progress in https://github.com/inlang/monorepo/pull/1385

**Comment by felixhaeberle** [comment]
@NiklasBuchfink can this be closed?
