### ISSUE TITLE
[bug] machine-translate is overriding values

### ISSUE THREAD

**Issue by mattupham** [opral/inlang#1435]
### Problem

Previously, running machine-translate would not override previous values if the key / value pair was populated. In the codebase we have some manual translations, and we don't want to override these. We recently upgraded inlang to the latest version. See this example after running machine-translate https://github.com/osmosis-labs/osmosis-frontend/pull/2226

### Expected behavior

machine-translate should not override key / value pairs if they exist, or so we thought

### Reproduction

1. run inlang machine-translate on repository
2. see many translation values updated

### Other information

"@inlang/cli": "^1.8.0",

**Comment by felixhaeberle** [comment]
Thanks for reporting. I'm looking into this!

**Comment by felixhaeberle** [comment]
@mattupham Can you again execute `npx @inlang/cli@latest machine translate` (to run on the latest version) and see if the issue persists? I could not reproduce it.
