### ISSUE TITLE
[bug] issues with newlines in keys newlines in keys

### ISSUE THREAD

**Issue by KraXen72** [opral/inlang#1702]
### Problem

default string:
```js
const testString = `there
are
multiple
lines`
```

1. extracted json has extra `\r`
`"testtest2": "there\r\n\tare\r\n\tmultiple\r\n\tlines"`

2. vs code extension: preview is cut off:
![image](https://github.com/inlang/monorepo/assets/21956756/0b3e2b6b-415c-4b2a-ae9b-818189335b79)

3. cli machine translation does not respect newlines:
```json
// other-lang.json
"testtest2": "there are multiple lines"
```

(yes i translated from english to english but disregard that for this example)

### Expected behavior

1. no unnecessary \r characters in keys
2. ellipsized preview, instead of cutoff, possibly showing (x more lines)
3. respect newlines in translation

### Reproduction

let me know if these issues need a minimal reprodoction other than the test string i provided.

### Other information

i had to downgrade the inlang extension to 1.17.0 due to #1700 
windows 10

@inlang/ide-extension

**Comment by samuelstroschein** [comment]
Keep the issues coming in :D Thank you!

**Comment by felixhaeberle** [comment]
@samuelstroschein how do we want to handle new lines in our message format?

**Comment by samuelstroschein** [comment]
> how do we want to handle new lines in our message format?

As regular Text. Seems like a bug in machine translate. The Google API seems to prune new lines. Maybe the need to be escapted

**Comment by felixhaeberle** [comment]
Sure, but escape them with /n ? Or simply don't handle them?

**Comment by samuelstroschein** [comment]
> Sure, but escape them with /n ? Or simply don't handle them?

I don't quite understand the question. The ide extension should include new lines. Machine translate should not prune new lines.

**Comment by KraXen72** [comment]
> Sure, but escape them with /n ? Or simply don't handle them?

i think the difference is that not handling them currently produces \r\n, and the other option is just \n. in my opinion, \n is cleaner and does the same job afaik

**Comment by felixhaeberle** [comment]
Got it, l'm on it.

**Comment by felixhaeberle** [comment]
@KraXen72 fixed 🎉

**Comment by KraXen72** [comment]
niiice 🤘
