### ISSUE TITLE
Improve SDK Documentation

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang#1815]
## Problem 
People that get to the SDK DOcs have different goals.
- Build an app on top of the SDK
- Develop a plugin
- Develop a lint rule
- Publish Content

## Proposal: Add a Navbar to get to each doc with (SDK, Plugin, Lint Rule, Publish Content). 

Pro: 
- Better sharable links for each goal
- Compact docs that are not overwhelming

Plan:
- [x] Plan pages (only title/ IA not exact content for everything)
- [x] log routes and save somewhere (to check rerouting later)
- [x] Add new table of contents 
- [x] Adjust markdown getter on server
- [x] Update Navigation in UI
- [x] Test UI
- [x] Redirect old pages to new content (if needed)

**Comment by NilsJacobsen** [comment]
Update Plan pages:
![image](https://github.com/inlang/monorepo/assets/58360188/566dc5fb-11b7-4c97-9801-f1c432716b97)

**Comment by NilsJacobsen** [comment]
Update old urls:
```
documentation/
documentation/architecture
documentation/build-app
documentation/build-plugin
documentation/build-lint-rule
documentation/publish-to-marketplace
documentation/publish-guide
documentation/sdk
documentation/comver
documentation/app
documentation/project
documentation/message
documentation/plugin
documentation/lint-rule
documentation/library
documentation/language-tag
```

**Comment by NilsJacobsen** [comment]
Update: https://www.loom.com/share/24f98ee1056f42a9a33f707888c3526c?sid=75c708db-23d3-4a12-a3aa-97809e5b4960

<img width="1512" alt="image" src="https://github.com/inlang/monorepo/assets/58360188/730f866c-6d70-4447-88e8-9ba91514cdc6">

Added plugin, lint rule and publish content will follow

**Comment by felixhaeberle** [comment]
@NilsJacobsen Great work! 😊

**Comment by NilsJacobsen** [comment]
Thanks, gonna work on it today. 
- add lint rules
- improve main navigation

**Comment by NilsJacobsen** [comment]
I'm gonna close this. @jldec we can open a new one when sdk becomes more stable

**Comment by jldec** [comment]
thanks @NilsJacobsen
I like that we have a starting point for SDK docs with a familiar sidebar layout.
It would be good to improve on that incrementally, adding new sections or pages one by one.
We also need to find a way to link from the main nav to the SDK docs.
