### ISSUE TITLE
[bug] Fink error during rendering after selecting a branch

### ISSUE THREAD

**Issue by jldec** [opral/inlang#2262]
### Problem

1. go to https://fink.inlang.com/github.com/opral/example
2. switch to another branch like "Add-missing-translations" ~~(branch is missing a /project.inlang/ folder)~~
3. if you don't see the error right away, reload your browser 

![Screenshot 2024-02-19 at 18 07 38](https://github.com/opral/monorepo/assets/849592/56a382bb-6a0e-45f0-8be8-f7560f9b0106)

### Expected behavior

no error in this case - just the initialize project reminder

### Reproduction

see above

**Comment by jldec** [comment]
I see this even for branches with the project.inlang folder
e.g. https://fink.inlang.com/github.com/jldec/paraglide and select the [first branch](https://github.com/jldec/paraglide/tree/PR2108_aliases_language_fallback)

**Comment by NiklasBuchfink** [comment]
I checked what's the issue here:
The project is set as a search param, but the project does not exist within this branch.

Fink needs to validate that a project exists in this branch before I try to open it. Even if it is set as in the URL.
