### ISSUE TITLE
Requirements for gender and plurals

### ISSUE THREAD

**Issue by jldec** [opral/inlang#3999]
### Context

Users are asking for inlang to support messages with variant for gender and plurals.

### Proposal

Introduce new types which are aligned with ICU Message Format 2 messages and a new message bundle type to collect messages translated for different locales.

**Comment by W1M0R** [comment]
This format for pluralization seems to be very flexible, in case this matches your goals: https://github.com/nicksnyder/go-i18n/blob/b42d9bd0c568eebf5ce123ec94b9b13438f46855/i18n/bundle_test.go#L101

![image](https://github.com/opral/inlang/assets/618853/23f15013-7a06-48a4-a02d-09185ca98a5f)

In this example, "simple", "detail", and "everything" are the translation keys, and "zero", "one", "two", "few", "many" and "other" are the different plural forms for the specific translation.
