### ISSUE TITLE
Move types of inlang (config) to @types / DefinitelyTypes repository

### ISSUE THREAD

**Issue by felixhaeberle** [opral/inlang#458]
## Problem

Hey, according to the docs I have to import the types for the inlang config from the core package.

https://inlang.com/documentation/getting-started

## Proposal

Should be move them to DefinitelyTypes repository?

https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by samuelstroschein** [comment]
> When there are errors, instead of installing inlang core as dev dependency, I would rather have a gut feeling to install @types/inlang to "fix it" from a dev perspective. 

Oh, that makes sense. 

The "correct way" to solve typings are dynamic import types like Deno has them. If the issue becomes pressing, we should rather contribute to TypeScript than hack a solution together as mentioned in https://github.com/inlang/inlang/discussions/431#discussioncomment-5221303%60. 

Closing this issue. Feel free to re-open.
