### ISSUE TITLE
logic to hook into .js/.ts files

### ISSUE THREAD

**Issue by ivanhofer** [opral/inlang#525]
In order to inject code we need some generic logic that makes it possible to hook into any file at certain places. e.g. we need to wrap the `handle` function of the `hooks.server.ts` file or the `load` function inside all `+page/+layout` files.

```ts
// original
export const load = () => {
   return { data: true }
}

// modified
import { wrapFn } from 'some/path'

export const load = wrapFn(() => {
   return { data: true }
})
```

This replacement should work on an AST and not regex. Take a look at `SvelteKit` and what they use for AST parsing.
Consider the input and output params that the plugin workflow requires.

**Comment by benjaminpreiss** [comment]
Soo, to just put some of my thought up for discussion here:

### Which parser to use

Rollup actually provides a parser `this.parse` for JS files via the plugin context. It uses rollups internal parser, which is acorn. That's also the parser that [AST explorer](https://astexplorer.net/) uses for JS files.

And as unplugin is based on the rollups plugin API, it is also available in unplugin 🎉 
For svelte files, we can then use the svelte parser.

### Function naming & mechanism

@ivanhofer as I understand, we need the function to just wrap another function, right? Or do we need other AST manipulations as well?

If we are talking about wrapping, I'd suggest we call the function `wrapFunctionDeclaration`. Then we could insert the necessary imports with another function that we call `insertAst` which inserts an AST at a **designated** position in the source AST.

#### `wrapFunctionDeclaration` might have the following type signature:

```ts
type wrapFunctionDeclaration = (
  sourceAst: ESTree.Program,
  searchIdentifier: string,
  identifier: string
) => ESTree.Program;
```

Where `searchIdentifier` is the identifier of the function declaration which should be wrapped and `identifier` is the identifier of the function used for wrapping.

So in the above example we have `searchIdentifier = load` and `identifier = wrapFn`.

#### `insertAst` might have the following type signature:

```ts
type insertAst = (
  sourceAst: ESTree.Program,
  ast: ESTree.Program,
  params: { before: string; after?: never } | { before?: never; after: string }
) => ESTree.Program;
```

Where `before` and `after` are identifying strings for an insertion position in the AST.
Example 1: `before: 'body[0]'` to insert into the AST body before the currently first element.
Example 2: `after: 'body[0].declarations[0]'` to insert after the first declaration in the first element of the body

#### Combining `insertAst` and `wrapFunctionDeclaration`

To achieve the desired result, we can then do:

```js
const ast = insertAst(wrapFunctionDeclaration(sourceAst, ...), ...)
```

Please let me know your thoughts on this @ivanhofer

**Comment by ivanhofer** [comment]
@benjaminpreiss sounds good!

**Comment by benjaminpreiss** [comment]
As these functions are not `sveltekit-adapter` specific, I would like to create the folder `sdk-js/src/helpers` to accomodate these functions. @ivanhofer are you fine with that?

**Comment by benjaminpreiss** [comment]
The way the code is working now, we can wrap variable declarations in general with the function `wrapFunctionDeclaration`. So I suggest a different naming - `wrapVariableDeclaration` or even `wrapVariableDeclarationValue`, as we are actually only wrapping the right side of the declaration. @ivanhofer ?

**Comment by benjaminpreiss** [comment]
Also, for my self here:

- [ ] Add JSDoc documentation for both exported functions
- [ ] Complete testing

**Comment by ivanhofer** [comment]
> As these functions are not `sveltekit-adapter` specific, I would like to create the folder `sdk-js/src/helpers` to accomodate these functions. @ivanhofer are you fine with that?

Yes

> The way the code is working now, we can wrap variable declarations in general with the function `wrapFunctionDeclaration`. So I suggest a different naming - `wrapVariableDeclaration` or even `wrapVariableDeclarationValue`, as we are actually only wrapping the right side of the declaration. @ivanhofer ?

Go for it
