### ISSUE TITLE
editor does not work

### ISSUE THREAD

**Issue by ivanhofer** [opral/inlang#567]
## Problem

The editor always tells me to fork my own repo

## Steps to reproduce

see video

https://user-images.githubusercontent.com/21335119/233412739-70816b2f-8157-41bc-a784-c7955bd8d014.mp4

**Comment by NilsJacobsen** [comment]
Is it possible that it used the main branch protection in your fork too? That would cause a behavior like this? @ivanhofer

**Comment by samuelstroschein** [comment]
The "isFork" logic seems flawed 

https://github.com/inlang/inlang/blob/0c6c8b1080ff69ca638fef498eec512b824cc059/source-code/website/src/pages/editor/@host/@owner/@repository/components/Gitfloat.tsx#L40-L44

Hahah basically, if a repo is not a fork, it should prompt to fork @NiklasBuchfink :D

**Comment by samuelstroschein** [comment]
i'll fix it. the code is wrong, shoulnd't use an effect anyways

**Comment by samuelstroschein** [comment]
i hope the bug has been fixed in 7cdf965. haven't tested 🤞 @NiklasBuchfink read my comment in the commit

**Comment by samuelstroschein** [comment]
@ivanhofer site has been deployed. does it work now?

**Comment by ivanhofer** [comment]
Yes, but found another bug ^^
https://github.com/inlang/inlang/issues/568
