### ISSUE TITLE
only trigger ci/cd to publish ide extension on package.json version change

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang#890]
## Problem

The ide extension publishing ci/cd is triggered with each change to the source code of the ide extension. That is annoying because tests are failing, see https://github.com/inlang/inlang/actions/runs/5186652655/jobs/9348037015. 

## Proposal

Only trigger the publishing ci/cd action if the version number in the package.json changes.

## Additional information

Another workflow already uses package version changes as a trigger. Might help as inspiration.

**Comment by felixhaeberle** [comment]
@samuelstroschein This has already been done.

https://github.com/inlang/inlang/commit/e45ca9918ccd5c5323ad87a2ff5123033c1fc5a7
