### ISSUE TITLE
Minimize bugs with tests, explicit namespaces and remove metadata

### ISSUE THREAD

**Issue by NilsJacobsen** [opral/inlang#996]
## Problem

Plugins just became too complex. In the last two months, we put a lot of effort into improving, testing, and debugging the plugins, but we still repeatedly run into the same problems.

## Challenges

- No metadata anymore for good reasons (new messages or languages do not have metadata)
- Key nesting (formatting) shouldn't result in a lot of changes
- Namespaces bring complexity
- Every app (Editor, CLI, IDE extension) needs to work

## Why should we care

-  In the last two months, plugins took a lot of time (debugging, features, testing)
-  Complexity is rising through implicit code
- We want the plugins to be in a kind of finished state for some weeks so we can focus on the next thing
- It should be fun to add features, it should be so easy that people can take over work

## Proposal

Make `PluginSettings` more explicit. Two significant points lead to high complexity. Namespaces & Formatting. Right now they get analyzed implicitly. But here's where the problems begin. I propose to set this information explicitly in the `PluginSettings` to take out the analyzing part. 

```ts
export type PluginSettings = {
	pathPattern: string | { [key: string]: string }
        format?: {
                space?: '\t' | number //default 2
                flatten?: boolean //default flat
        }
	variableReferencePattern?: [string] | [string, string]
	ignore?: string[]
}
```

#### Example without namespaces and space 2 and flat keys

```ts
const pluginSettings = {
	pathPattern: "locales/{language}.json",
}
```

#### Example with namespaces and space 2 and flat keys

```ts
const pluginSettings = {
	pathPattern: {
	        "common": "locales/{language}/common.json",
	        "cards": "locales/{language}/cards.json",
	 }
}
```

#### Example with monorepo and space 2 and flat keys

```ts
const pluginSettings = {
	pathPattern: {
	        "projectA": "projectA/locales/{language.json",
	        "projectB": "projectB/locales/{language}.json",
	 }
}
```

#### Example without namespaces and space `\t` and nested keys

```ts
const pluginSettings = {
	pathPattern: "locales/{language}.json",
	format: {
	        space: '\t',
	        flatten: false,
        }
}
```

**Pros:**
- That should make the plugins significantly more stable
- Better maintenance
- less complexity
- less code
- better performance
- Fix monorepo support

**Cons:**
- If we change the API, we have braking changes (As we are focusing on fewer but bigger projects I feel like that might be okay)
- Less smart detection (what doesn't work is not smart)

## Conclusion 
I feel like that could help us. Goal for next week: No need to work on the plugins. So let's fix it. 

Related issues (u see it is urgend): 
https://github.com/inlang/inlang/issues/874#issuecomment-1606816605
https://github.com/inlang/inlang/issues/976
https://github.com/inlang/inlang/issues/985
https://github.com/inlang/inlang/issues/966

**Comment by NilsJacobsen** [comment]
@inlang/team

**Comment by NilsJacobsen** [comment]
Gonna update the title -> focus shifted a bit.

Old focus: Make it more explicit because plugins get too complicated
New focus: Remove metadata, keep space/endsWithNewLine, make namespaces/nested explicit, add tests
In general -> make plugin more reliable/maintainable with tests, explicit namespaces and remove metadata

**Comment by felixhaeberle** [comment]
Hi, wanted to weigh in here & think inlang should not be an expert company in json parsing. 

That said, providing standard formatting should be considered, and whoever considers inlang will probably not sip it because it has this potential one-time formatting change. This is simply the adoption cost, and it's not that high. 

We also provide them with `lint`, remember? So Quality Control is built into inlang.

I'm very curious if we can properly parse round-trip such an example:

```json
{
  "name": "John Doe",
  "age": 30,
  "city": "New York",
  "person": {
    "name": "John Doe",
    "age": 30,
    "city": "New York"
  },
  "fruits": [
    "apple",
    "banana",
    "orange"
  ],
  "employees": [
    {
      "firstName": "John",
      "lastName": "Doe"
    },
    {
      "firstName": "Jane",
      "lastName": "Smith"
    }
  ],
  "company": {
    "name": "ABC Inc.",
    "address": "123 Main St",
    "city": "New York"
  },
  "{}": {},
  "[]": [],
  "formatted": {
    "name": "John Doe",
    "age": 30,
    "city": "New York"
  },
  "trailingComma": {
    "name": "John Doe",
    "age": 30,
    "city": "New York",
  },
  "singleQuotes": {
    'name': 'John Doe',
    'age': 30,
    'city': 'New York'
  },
  "multiLineString": {
    "description": "This is a\nmulti-line\nstring."
  },
  "//Comments": {
    // This is a comment
    "name": "John Doe",
    "age": 30,
    "city": "New York"
  },
  "compact": {"name":"John Doe","age":30,"city":"New York"},
  "numbersAndBooleans": {
    "count": 10,
    "isTrue": true,
    "pi": 3.14
  },
  "nullValues": {
    "name": null,
    "age": null
  },
  "escapingCharacters": {
    "message": "Escape \"quotes\" and use \\ to escape special characters."
  },
  "unicodeCharacters": {
    "emoji": "\uD83D\uDE00",
    "currency": "€"
  },
  "dateAndTime": {
    "timestamp": "2023-06-28T12:34:56Z"
  },
  "jsonWithMetadata": {
    "metadata": {
      "createdBy": "John Doe",
      "createdDate": "2023-06-28",
      "version": 1
    },
    "data": {
      "name": "John",
      "age": 30
    }
  }
}
```

**Comment by NilsJacobsen** [comment]
The json examples is not working, because we do not support arrays. 

I feel like the plugin is getting to a nicely tested, maintainable and bug resistant state. 

Update on formatting: we implicitly detect formatting only on a file level and store it in the plugin state. Nothing is stored in the metadata anymore.

**Comment by NilsJacobsen** [comment]
I like the idea of testing that kind of syntax edge cases in one test.

**Comment by NilsJacobsen** [comment]
Will be merged in this PR: https://github.com/inlang/inlang/pull/1015
